### ISSUE TITLE
api prefix 설정

### ISSUE THREAD

**Issue by rlaisqls** [EntryDSM/Equus-Config-Server#1]
https://github.com/EntryDSM/Equus-Config-Server/blob/5bcc4b575931668b108093a3db8ff44550ecc55b/src/main/kotlin/hs/kr/equus/configserver/RedirectController.kt#L12

이거 redirect로 처리하지 않고 application.yaml 파일 cloud config server 부분에 prefix 설정해주어서 요청 가도록 처리하면 어떨까요?

```yaml
spring:
  cloud:
    config:
      server:
        ...
        prefix: equus-config
```

아니면 prefix 설정을 하지 않고 xquare 배포시에 커스텀 도메인(ex: `equus-config.xquare.app`)을 설정해서 사용하는 방법도 있을 것 같아요.
